### ISSUE TITLE
建议增加 .Net Standard 2.0 支持

### ISSUE THREAD

**Issue by yejinmo** [taosdata/taos-connector-dotnet#20]
根据 [https://docs.microsoft.com/zh-cn/dotnet/standard/net-standard?tabs=net-standard-2-0](https://docs.microsoft.com/zh-cn/dotnet/standard/net-standard?tabs=net-standard-2-0) 可知，.Net Standard 2.0 是整个 .Net 体系中目标最广的一组规范。

在当今国产化趋势中，仍有很多技改项目运行较旧版本的 Windows 系统，此部分系统因兼容性原因仅能使用 .Net Framework，增加 .Net Standard 2.0 目标可以很好的支持这些系统。

**Comment by maikebing** [comment]
支持 .Net Standard 2.0 

https://github.com/IoTSharp/EntityFrameworkCore.Taos
