### ISSUE TITLE
内存占用会不断的升高（Memory Leak）

### ISSUE THREAD

**Issue by GrandMarch** [taosdata/taos-connector-dotnet#32]
按照https://docs.taosdata.com/develop/insert-data/sql-writing/ 的例子，进行sql写入会导致内存缓慢的升高。怀疑某些intptr没有正确的释放。

**Comment by GrandMarch** [comment]
执行res = TDengine.Query(conn, "USE power");
需要手动调用TDengine.FreeResult(res)
官网给的C#的例子中没用调用TDengine.FreeResult,但是我发现官网的C/C++的例子中调用了taos_free_result()。
调用TDengine.FreeResult(res)后内存几乎没用大的变化，看上去已经不再泄露了。

**Comment by sangshuduo** [comment]
> 执行res = TDengine.Query(conn, "USE power"); 需要手动调用TDengine.FreeResult(res) 官网给的C#的例子中没用调用TDengine.FreeResult,但是我发现官网的C/C++的例子中调用了taos_free_result()。 调用TDengine.FreeResult(res)后内存几乎没用大的变化，看上去已经不再泄露了。

谢谢指出。提了一个 PR: https://github.com/taosdata/TDengine/pull/16771
