### ISSUE TITLE
找不到指定模块taosdata.dll

### ISSUE THREAD

**Issue by tengxinlin** [taosdata/taos-connector-dotnet#42]
引用TDengine.connector.test程序包建立websocket连接报错：
"无法加载 DLL“/d/git_space/work/3.0/taos-connector-rust/target/release/taosws.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。"

**Comment by sangshuduo** [comment]
TDengine 什么版本？

**Comment by tengxinlin** [comment]
TDengine是2.6版本的，TD engine.connector.test程序包是9.0.5版本，
在命名空间TDengineWS.Impl的LibTaosWS类中存在一个 public const string LibName = "/d/git_space/work/3.0/taos-connector-rust/target/release/taosws.dll"，怀疑是这个全局常量引起的异常。

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/connector/#%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81

![image](https://user-images.githubusercontent.com/825729/204945401-9e56250f-4888-4412-8f4c-d570f03b1f40.png)

**Comment by tengxinlin** [comment]
https://github.com/taosdata/taos-connector-dotnet/tree/3.0
是否意味着我这个当前版本的TDengine并不支持C#建立websocket连接
![QQ截图20221201095208](https://user-images.githubusercontent.com/107337290/204947003-92111c19-010c-49b5-ab7e-417b681bff70.png)

**Comment by sangshuduo** [comment]
> 

是的

**Comment by tengxinlin** [comment]
因为实验室也是在刚使用TDengine，目前TDengine版本2.6，程序目标框架.net4.7，想着用C#建立websocket连接，不用原生连接，这样就不需要下载TDengine客户端驱动。因为目前用的TDengine版本是2.6版本的，所以TDengine.Connector连接器的版本应该在1.0.2-1.0.6之间选取，但是由于我目前程序的框架是.net4.7，选取的TDengine.Connector连接器的版本是1.0.4
![image](https://user-images.githubusercontent.com/107337290/204956803-02e04841-5654-418e-a8ad-51167c2a25da.png)
![image](https://user-images.githubusercontent.com/107337290/204957224-9a5d2e61-fdc5-4bf4-8d25-bf794acb7a19.png)

疑问1：
但是TDengine.Connector V1.0.4里并没有建立websocket连接的命名空间TDengineWS.Impl，所以按照我目前的TDengine版本与程序框架，是不是用TDengine.Connector就不能建立websocket连接？

疑问2：
NuGet程序包里有一个相同作者发布的TDengine.Connector.test包，里面刚好有建立websocket连接的命名空间TDengineWS.Impl，而且与我程序的框架也兼容，所以我换了TDengine.Connector.test，但似乎也建立不了websocket连接，调试五分钟后才会抛出异常，请问TDengine.Connector与TDengine.Connector.test有什么区别？是不是我不该使用TDengine.Connector.test这个包？

疑问3：
C#连接器TDengine.connector目前版本到3.0.1版本，TDengine目前版本到3.0.1.8版本，按照此链接的文档https://github.com/taosdata/taos-connector-dotnet/tree/3.0
它里面提示Tips: TDengine.Connector support WebSocket from V3.0.2. And for v1.x doesn't support WebSocket.（也就是上面那张图里圈出来的），因为NuGet程序包里根本没有TDengine.Connector V3.0.2，是不是可以理解C#就不能建立websocket连接啊？

还请作者大大解决下疑惑，感谢！

**Comment by xleili** [comment]
疑问1：
TDengine.Connector V1.X, 不支持建立websocket 连接，

疑问2：
TDengine.Connector.test 这个是我测试用的，也是基于TDengine.Connector V3.x ,需要时使用TDengine v3.0.0.0 及以上。不该使用这个包。

疑问3：
TDengine.Connector V3.0.2 这个版本还没有发布，是因为所依赖的websocket 动态库，再windows上的有bug，最近才修复。我还没来及验证。

建议：
我看您想使用的是 .Net Framework
这个下次发版的时候，V1.x 和V 3.x 都会支持，Framework 4.5 及以下上，可以稍微等一下。

另外如果想使用websocket有如下两个办法：
1.按照目前已有的包，需要使用TDengine V3.0.1，然后安装 TDengine Windows client 或者 client， V3.0.1.8。

2.或者等我验证完windows的 taosws.dll，就会发布TDengine V3.0.2，那时候nupkg中会包含taosws.dll,可以直接使用。

**Comment by tengxinlin** [comment]
谢谢作者解答了
