### ISSUE TITLE
使用3.0版本的c#驱动可以连接旧版本的TDengine吗？

### ISSUE THREAD

**Issue by JavenJin** [taosdata/taos-connector-dotnet#47]
使用3.0版本的c#驱动可以连接旧版本的TDengine吗？

**Comment by JavenJin** [comment]
我想写一个可以同时连接2.6和3.0版本TDengine数据库的连接器，貌似无法做到

**Comment by sangshuduo** [comment]
难度很大，因为 taosc 的接口不完全一致，所以需要加载 2.6 和 3.0 不同的 share library

**Comment by JavenJin** [comment]
当我使用3.0.2的C#驱动，分别连接3.0.1.0和3.0.2.4版本的TDengine时，仍需要加载不同版本的taos.dll ?

而当我想要连接3.0以前版本的TDengine时，我就应该使用1.0.8的驱动，同时加载对应版本的taos.dll ?

这样说对吗？还是说对某些版本来说，可能并不可以使用3.0.2或1.0.8驱动连接，而需要使用其他版本？

**Comment by sangshuduo** [comment]
taos.dll 和 taosd 的版本在 3.0.2.0 之前要求版本完全一致，之后会保证版本号前三位相同时兼容

**Comment by JavenJin** [comment]
好的，明白了，谢谢。

**Comment by JavenJin** [comment]
@sangshuduo 
TDengine 2.6 版本的 taos.dll 文件是通用的吗？

因为我尝试用2.6.0.0版本的taos.dll文件成功查询了2.6.0.0、2.6.0.1、2.6.0.4、2.6.0.34这几个版本，但我还不太确定。

**Comment by JavenJin** [comment]
@sangshuduo 
如果不通用的话，我还想知道是否我使用2.6.0.34的taos.dll就可以兼容之前的版本呢？

**Comment by sangshuduo** [comment]
不通用，不兼容。需要使用和服务端完全一致的版本
