### ISSUE TITLE
释放连接后重新创建连接失败

### ISSUE THREAD

**Issue by JavenJin** [taosdata/taos-connector-dotnet#48]
TDengine版本：2.6.0.28
TDengineDriver版本：1.0.8
TDengine Client版本：2.6.0.28

![image](https://user-images.githubusercontent.com/59432060/219994966-bf024820-45ca-4896-90c9-ed10b97417ad.png)

如上图，重新连接失败！是需要在释放时做更多的处理吗？

**Comment by xleili** [comment]
TDengine.Cleanup() 只需要在程序的退出的时候调用一次就好。不需要每次连接都调用
调用该函数会 cleanup client environment。

**Comment by JavenJin** [comment]
@xleili 你好我遇到了问题
如下的代码会在第18行报错，但我不知道该如何修复它。

![image](https://user-images.githubusercontent.com/59432060/223348165-2a95fa7e-af3d-4347-b72b-d9b6636cb353.png)

TDengine版本：2.6.0.28
TDengineDriver版本：1.0.8
TDengine Client版本：2.6.0.28

**Comment by xleili** [comment]
18 行的异常信息是 连接失败的信息吗？还是有别的异常？

**Comment by JavenJin** [comment]
报错的原因是因为connection2的值是IntPtr.Zero
![image](https://user-images.githubusercontent.com/59432060/223403075-6fdf7d88-7ea8-474c-b4c6-49f3191f7a7f.png)
设置debugFlag 135后日志报错如下：
![image](https://user-images.githubusercontent.com/59432060/223403805-c22f9951-a0fa-405a-9824-e44dfb948ea5.png)


日志附件：
[log.zip](https://github.com/taosdata/taos-connector-dotnet/files/10908633/log.zip)

**Comment by xleili** [comment]
日志再发一下吧，附件是个空文件夹

**Comment by JavenJin** [comment]
抱歉

[log.zip](https://github.com/taosdata/taos-connector-dotnet/files/10915348/log.zip)

**Comment by xleili** [comment]
> 抱歉
> 
> [log.zip](https://github.com/taosdata/taos-connector-dotnet/files/10915348/log.zip)

收到了

**Comment by xleili** [comment]
![image](https://user-images.githubusercontent.com/85657333/223903585-6585da1b-95ee-4323-95a9-2dddb7261c4c.png)
我自己按照你的提供的版本跑了一下，没有碰到问题。
我看log中显示，第一连接成功了，第二连接失败了。应该是不是连接器的问题，可以在检查一下，服务端这个期间是不是有问题。


![image](https://user-images.githubusercontent.com/85657333/223903958-bc134cf7-d991-455c-a12b-5909b280ab42.png)
消息是发送了，但是没有收到响应。

**Comment by JavenJin** [comment]
好的，谢谢，应该是连接不稳定的原因。
我发现当我在taos.cfg中添加下面的配置后就不会报错了

rpcForceTcp 1
