### ISSUE TITLE
error:some vnode/qnode/mnode(s) out of service

### ISSUE THREAD

**Issue by hyzgit** [taosdata/taos-connector-dotnet#53]
07/18 15:02:16.271859 00044800 QRY catalog update thread started
07/18 15:02:16.271859 00053148 QRY scheduler 0x41373343303043 initizlized, maxJob:1000
07/18 15:02:16.275632 00053148 TSC connecting to server, numOfEps:1 inUse:0 user:root db: key:root:dcc5bed04851fec854c035b2e40263b6:106.23.79.186:6030
07/18 15:02:16.275632 00053148 TSC ep:0, 106.23.79.186:6030
07/18 15:02:19.339513 00062628 RPC ERROR TSC msg vnode-batch-meta failed to send, conn 00000153EBB83B50 failed to connect to 106.53.79.86:6030, reason: operation canceled, gtid:0x198bc4ce89fd0002:0xe4167ce8a00004
07/18 15:02:22.338974 00062628 RPC ERROR TSC msg vnode-batch-meta failed to send, conn 00000153EBB82590 failed to connect to 106.53.79.86:6030, reason: operation canceled, gtid:0x198bc4ce89fd0002:0xe4167ce8a00004
07/18 15:02:25.350374 00062628 RPC ERROR TSC msg vnode-batch-meta failed to send, conn 00000153EBB83980 failed to connect to 106.53.79.86:6030, reason: operation canceled, gtid:0x198bc4ce89fd0002:0xe4167ce8a00004
07/18 15:02:28.371259 00062628 RPC ERROR TSC msg vnode-batch-meta failed to send, conn 00000153EBB83980 failed to connect to 106.53.79.86:6030, reason: operation canceled, gtid:0x198bc4ce89fd0002:0xe4167ce8a00004
07/18 15:02:31.411474 00062628 RPC ERROR TSC msg vnode-batch-meta failed to send, conn 00000153EBB82EA0 failed to connect to 106.53.79.86:6030, reason: operation canceled, gtid:0x198bc4ce89fd0002:0xe4167ce8a00004
07/18 15:02:31.411474 00057088 QRY ERROR Got error rsp, error:some vnode/qnode/mnode(s) out of service
07/18 15:02:31.411474 00057088 QRY ERROR QID:198bc4ce89fd0002 CTG:00000153EA2BED80 Get table 1.mediacloud.userlog meta failed with error some vnode/qnode/mnode(s) out of service
07/18 15:02:31.411474 00063156 TSC ERROR 0x3 error happens, code:-2147483616 - some vnode/qnode/mnode(s) out of service, reqId:0x198bc4ce89fd0002

**Comment by sangshuduo** [comment]
这个问题和连接器没什么关系，需要检查 log 是否是环境问题，TDengine 这边有什么操作。建议到 TDengine 仓库提一个 issue 并提供相关信息
